### PR TITLE
accessibility fixes

### PR DESCRIPTION
**Pull request by mel-miller**
and other small theme adjustments

### CODE REVIEW

**Comment by mel-miller** [comment]
Includes issues: #54, #27

**Comment by mel-miller** [comment]
added issue: #67

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3062371

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3062371#comment-13150514

**Pull request merged**
