### PR TITLE
Registration Page Items

### PR DESCRIPTION
**Pull request by sean-e-dietrich**

### CODE REVIEW

**Comment by sean-e-dietrich** [comment]
@mel-miller this should be good for page 1 of registration

**Comment by mel-miller** [comment]
@sean-e-dietrich Is it cool if I commit to the theme directory on this branch?

**Comment by sean-e-dietrich** [comment]
@mel-miller sure ... whatever you need to do i think that is cool!

**Comment by sean-e-dietrich** [comment]
@mel-miller the sponsor page is set to be themed you can access it by logging in and going to `/registration/sponsor`

**Comment by mel-miller** [comment]
@sean-e-dietrich -- I believe that I am done committing to this branch. I'll be theming the sessions in a different branch.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3070395

**Pull request merged**
