### PR TITLE
#29 - exported db config to disk

### PR DESCRIPTION
**Pull request by torenware**
Syncing the config/ directory to today's dev.badcamp-2019.sql.

### CODE REVIEW

**Comment by torenware** [comment]
Best way to validate this is using drush cst.  For files in sync with the db's configuration, you should get a result like:

```
$ fin drush cst
 [notice] No differences between DB and sync directory.
```

**Comment by torenware** [comment]
Let me rebase...

**Comment by torenware** [comment]
It would appear that with yesterday's checkins, the database configuration was pushed to the config directory, which makes this PR redundant.  

It would be nice if when a PR is pushed, that it gets *some* response from the project lead. @sean-e-dietrich: what is your policy on review?  Once I get that, I'll close this issue.

**Comment by sean-e-dietrich** [comment]
@torenware my apology for the lack of communication. Not sure if I mentioned this to you but live is completely going away as we are doing new design and all around new install. Therefore most of the config files in live are no longer valid. I wasn't purposely ignoring it. I must have missed it as it wasn't on the project board and wasn't in the issues. Will try to be more diligent in responding to individual PRs in the future.

**Comment by sean-e-dietrich** [comment]
You are correct though this is no longer necessary and is redundant.

**Pull request closed without merging**
